#!/usr/bin/env bash
# configuration of domain and subdomain
subdomain="$2"
domain="$1"
if [ $# = 1 ];
then
        for x in "www" "lb-01" "web-01" "web-02"; do
        dig $x.$domain | grep -A1 'ANSWER SECTION:' > "file"
        awk -v x="$x" 'NR == 2 {print "The subdomain "x" is a "$4" record and points to "$5}' file
done
else
        dig $subdomain.$domain | grep -A1 'ANSWER SECTION:' > "file"
        awk -v x="$subdomain" 'NR == 2 {print "The subdomain "x" is a "$4" record and points to "$5}' file
fi
